# Generated by Django 4.2.4 on 2023-09-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('record', models.CharField(max_length=50)),
                ('is_retired', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_champ', models.BooleanField(default=True)),
                ('is_currect_champ', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=2000)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.styles')),
            ],
        ),
    ]
